<?php
/**
 * Create Time: 2021/4/10 13:50
 * Author:Liu Jiabing.
 * Email:531288693@qq.com
 */

namespace app\api\controller;
use app\api\model\UserAddress;
use app\Request;


class Address extends Base
{
    //用户信息
    private $user;
    //地址模型
    private $model;

    /**
     * 初始化获取用户信息与地址model
     * @throws \app\common\exception\BaseException
     * @throws \think\exception\DbException
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user=$this->getUser();
        $this->model=new UserAddress;
    }

    /**
     * 获取收货地址数据
     * @return array
     * @throws \app\common\exception\BaseException
     * @throws \think\exception\DbException
     */
    public function lists(){
        $list=$this->model->getList($this->user['user_id']);
        return $this->renderSuccess([
            'list' => $list,
            'default_id' => $this->user['address_id'],
        ]);
    }

    /**
     * 添加地址
     * @return array
     */
    public function add(){
        $this->model=new UserAddress();
        if($this->model->add($this->user,request()->post())){
            return $this->renderSuccess([], '添加成功');
        }
        return  $this->renderError([], '添加成功');
    }

    /**查询地址
     * @param $address_id
     * @return array
     * @throws \think\exception\DbException
     */
    public function detail($address_id){

        $detail=UserAddress::detail($this->user['user_id'], $address_id);
        $region = array_values($detail['region']);
        return $this->renderSuccess(compact('detail', 'region'));
    }

    /**修改地址
     * @param $address_id
     * @return array
     * @throws \think\exception\DbException
     */
    public function edit($address_id){

        $this->model=UserAddress::detail($this->user['user_id'], $address_id);
        return $this->checkReturn('edit',request()->post());
    }

    /**删除地址
     * @param $address_id
     * @return array
     * @throws \think\exception\DbException
     */
    public function delete($address_id){
        $this->model = UserAddress::detail($this->user['user_id'], $address_id);
        return $this->checkReturn('remove',$this->user);
    }

    /**
     * 默认地址
     * @param $address_id
     * @return array
     * @throws \think\exception\DbException
     */
    public function setDefault($address_id){

        $this->model = UserAddress::detail($this->user['user_id'], $address_id);
        return $this->checkReturn('setDefault',$this->user);
    }

    /**
     * 传入方法及方法需要的参数
     * @param $method
     * @param $param
     * @return array
     */
    private function checkReturn($method,$param){
        if ($this->model->$method($param)) {
            return $this->renderSuccess([], '操作成功');
        }
        return $this->renderError('操作成功');
    }
}